/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/tasks": {
    get: {
      parameters: {
        query: {
          /** Фильтр по важности задач */
          isImportant?: boolean;
          /** Поиск задач по названию (регистронезависимый) */
          name_like?: string;
          /** Фильтр по завершенности задач */
          isCompleted?: boolean;
        };
      };
      responses: {
        /** Успешный ответ */
        200: {
          content: {
            "application/json": components["schemas"]["Task"][];
          };
        };
        /** Ошибка сервера */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    post: {
      responses: {
        /** Задача создана */
        201: {
          content: {
            "application/json": components["schemas"]["Task"];
          };
        };
        /** Неверные данные */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Ошибка сервера */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateTask"];
        };
      };
    };
  };
  "/tasks/{id}": {
    get: {
      parameters: {
        path: {
          /** ID задачи */
          id: number;
        };
      };
      responses: {
        /** Успешный ответ */
        200: {
          content: {
            "application/json": components["schemas"]["Task"];
          };
        };
        /** Неверный ID */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Задача не найдена */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Ошибка сервера */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** ID задачи */
          id: number;
        };
      };
      responses: {
        /** Задача удалена */
        200: {
          content: {
            "application/json": components["schemas"]["Task"];
          };
        };
        /** Неверный ID */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Задача не найдена */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Ошибка сервера */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          /** ID задачи */
          id: number;
        };
      };
      responses: {
        /** Задача обновлена */
        200: {
          content: {
            "application/json": components["schemas"]["Task"];
          };
        };
        /** Неверные данные */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Задача не найдена */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** Ошибка сервера */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateTask"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Task: {
      /** @example 1 */
      id?: number;
      /** @example Сделать домашку по запросам */
      name?: string;
      /** @example Использовать патерн controller */
      info?: string;
      /** @example true */
      isImportant?: boolean;
      /** @example false */
      isCompleted?: boolean;
    };
    CreateTask: {
      /** @example Новая задача */
      name: string;
      /** @example Описание задачи */
      info?: string;
      /** @example false */
      isImportant?: boolean;
      /** @example false */
      isCompleted?: boolean;
    };
    UpdateTask: {
      /** @example Обновленное название */
      name?: string;
      /** @example Обновленное описание */
      info?: string;
      /** @example true */
      isImportant?: boolean;
      /** @example true */
      isCompleted?: boolean;
    };
    Error: {
      /** @example Сообщение об ошибке */
      error?: string;
    };
  };
}

export interface operations {}

export interface external {}
